services:
  frontend:
    image: rizqirafa8/nextjsapps:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: rizqirafa8/go-be-api:latest
    ports:
      - "8080:8080"
    env_file:
      - ./be-go/cmd/.env
    restart: unless-stopped
    networks:
    - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-collector
    volumes:
      - ./be-go/otel-config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "9464:9464"
    depends_on:
      - jaeger
    restart: always
    networks:
      - observability
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - "16686:16686"
    restart: always
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./be-go/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--web.enable-remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - monitoring
      - observability
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - jaeger
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - monitoring
      - observability

networks:
  observability:
  monitoring: